const { buildMarketPack } = require('./marketPack');
const { generatePost } = require('./generator');
const { publishToBinanceSquare } = require('./publisher');
const { sendTelegram } = require('./telegram');
const { appendRun, getSettings, saveSettings, getCounter, incrementCounter, listRuns } = require('./store');
const { selectImagePaths } = require('./imageAssets');

function hasBannedSymbol(pack, settings) {
  const banned = new Set((settings.bannedSymbols || []).map(s => String(s).toUpperCase()));
  return [pack.trio?.lead?.symbol, pack.trio?.peer?.symbol, pack.trio?.anchor?.symbol].filter(Boolean).find(s => banned.has(String(s).toUpperCase()));
}

function formatTime(tz = 'Asia/Shanghai') {
  return new Intl.DateTimeFormat('sv-SE', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(new Date());
}

function dayKey(date = new Date(), tz = 'Asia/Shanghai') {
  return new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
}

function countAutoImagePublishedToday(settings = {}) {
  const today = dayKey(new Date(), settings.timezone || 'Asia/Shanghai');
  return listRuns(500)
    .filter(r => r.status === 'published' && r.media?.autoGenerated === true && r.createdAt)
    .filter(r => dayKey(new Date(r.createdAt), settings.timezone || 'Asia/Shanghai') === today)
    .length;
}

function decideAutoImageForLiveRun(settings = {}) {
  const autoImageDailyLimit = Math.max(0, Number(settings.autoImageMaxDaily ?? 20));
  const autoImageDailyCount = countAutoImagePublishedToday(settings);
  const maxDailyPosts = Math.max(1, Number(settings.maxDailyPosts || 50));
  const counter = getCounter(settings);
  const remainingPosts = Math.max(1, maxDailyPosts - Number(counter.count || 0));
  const remainingImages = Math.max(0, autoImageDailyLimit - autoImageDailyCount);

  if (autoImageDailyLimit <= 0) {
    return {
      attach: false,
      selectionMode: 'random_spread',
      autoImageDailyLimit,
      autoImageDailyCount,
      remainingPosts,
      remainingImages,
      probability: 0,
      roll: null,
      skippedReason: 'auto_image_limit_zero'
    };
  }
  if (remainingImages <= 0) {
    return {
      attach: false,
      selectionMode: 'random_spread',
      autoImageDailyLimit,
      autoImageDailyCount,
      remainingPosts,
      remainingImages,
      probability: 0,
      roll: null,
      skippedReason: 'auto_image_daily_limit_reached'
    };
  }

  const probability = remainingImages >= remainingPosts ? 1 : (remainingImages / remainingPosts);
  const roll = Math.random();
  const attach = roll < probability;
  return {
    attach,
    selectionMode: 'random_spread',
    autoImageDailyLimit,
    autoImageDailyCount,
    remainingPosts,
    remainingImages,
    probability: Number(probability.toFixed(4)),
    roll: Number(roll.toFixed(4)),
    skippedReason: attach ? null : 'auto_image_random_skip'
  };
}

async function configuredMedia(settings = {}, pack = null, generated = null, { livePublish = false } = {}) {
  if (settings.enableImagePosts !== true) return { imagePaths: [], autoGenerated: false, autoImageDailyCount: countAutoImagePublishedToday(settings), autoImageDailyLimit: Number(settings.autoImageMaxDaily || 20) };
  const paths = [];
  let autoGenerated = false;
  const autoImageDailyLimit = Math.max(0, Number(settings.autoImageMaxDaily ?? 20));
  const autoImageDailyCount = countAutoImagePublishedToday(settings);

  if (settings.autoGenerateImage === true) {
    const minImageEvidenceScore = Number(settings.minImageEvidenceScore ?? 58);
    const evidenceType = pack?.marketEvent?.imageType || null;
    const evidenceQualified = Boolean(evidenceType) && Number(pack?.publishScore || 0) >= minImageEvidenceScore;
    if (settings.evidenceImagesOnly !== false && !evidenceQualified) {
      return {
        imagePaths: [], autoGenerated: false, autoImageDailyCount, autoImageDailyLimit,
        selectionMode: 'evidence_only', skippedReason: evidenceType ? `image_evidence_score_low:${pack?.publishScore || 0}/${minImageEvidenceScore}` : 'no_evidence_image_available'
      };
    }
    if (livePublish) {
      const decision = decideAutoImageForLiveRun(settings);
      if (!decision.attach) {
        return { imagePaths: [], autoGenerated: false, ...decision };
      }
    }
    if (pack && generated && autoImageDailyLimit > 0) {
      try {
        const { generateMarketCard } = require('./imageCard');
        paths.push(await generateMarketCard(pack, generated.text));
        autoGenerated = true;
      } catch (err) {
        console.error(`[media] auto image generation failed: ${err.message || err}`);
      }
    }
    return {
      imagePaths: paths.slice(0, 1),
      autoGenerated,
      autoImageDailyCount,
      autoImageDailyLimit,
      selectionMode: livePublish ? 'random_spread' : 'preview_force_generate'
    };
  }

  const maxCount = Math.max(1, Math.min(4, Number(settings.imagePathCount || 1)));
  paths.push(...selectImagePaths({ ...settings, imagePathCount: maxCount }, getCounter(settings).count));
  return { imagePaths: paths.slice(0, 4), autoGenerated: false, autoImageDailyCount, autoImageDailyLimit };
}

async function runOnce(mode = 'dry-run', meta = {}) {
  const startedAt = Date.now();
  const settings = getSettings();
  let pack = null;
  let generated = null;
  try {
    const counter = getCounter(settings);
    if (counter.count >= Number(settings.maxDailyPosts || 50)) throw new Error(`daily_limit_reached:${counter.count}/${settings.maxDailyPosts}`);

    pack = await buildMarketPack();
    if (!pack?.ok || !pack?.trio?.lead || !pack?.trio?.peer || !pack?.trio?.anchor) throw new Error('invalid_market_pack');
    const banned = hasBannedSymbol(pack, settings);
    if (banned) throw new Error(`banned_symbol_in_trio:${banned}`);

    // A valid live market pack must continue to content generation. The score is
    // editorial metadata and an image-evidence threshold, not a post-volume gate.
    // Previously this branch skipped roughly half of the scheduled runs whenever
    // the market was quiet, which made the configured daily quota unreachable.
    const minPublishScore = Number(settings.minPublishScore ?? 42);
    const qualityReference = {
      score: Number(pack.publishScore || 0),
      threshold: minPublishScore,
      belowReference: Number(pack.publishScore || 0) < minPublishScore
    };

    generated = await generatePost(pack);
    const livePublish = mode === 'publish' && settings.publishMode === 'live';
    const media = await configuredMedia(settings, pack, generated, { livePublish });
    const imagePaths = media.imagePaths;
    if (!livePublish) {
      return appendRun({
        mode: mode === 'publish' ? 'preview' : mode,
        requestedMode: mode,
        publishMode: settings.publishMode,
        status: 'preview',
        durationMs: Date.now() - startedAt,
        source: pack.source,
        lead: pack.trio.lead.symbol, peer: pack.trio.peer.symbol, anchor: pack.trio.anchor.symbol,
        postText: generated.text, promptId: generated.promptId, promptName: generated.promptName,
        provider: generated.provider, channelId: generated.channelId, channelName: generated.channelName, model: generated.model,
        llmAttempts: generated.attempts,
        media: { enabled: settings.enableImagePosts === true, ...media },
        publishScore: pack.publishScore, marketEvent: pack.marketEvent, qualityReference,
        facts: pack.facts, takeaways: pack.takeaways, meta
      });
    }

    const published = await publishToBinanceSquare(generated.text, { imagePaths });
    const nextCounter = incrementCounter({ url: published.url, symbol: pack.trio.lead.symbol }, settings);
    const row = appendRun({
      mode, status: 'published', durationMs: Date.now() - startedAt, source: pack.source,
      lead: pack.trio.lead.symbol, peer: pack.trio.peer.symbol, anchor: pack.trio.anchor.symbol,
      postText: generated.text, url: published.url, postId: published.id,
      promptId: generated.promptId, promptName: generated.promptName,
      provider: generated.provider, channelId: generated.channelId, channelName: generated.channelName, model: generated.model,
      llmAttempts: generated.attempts,
      media: { enabled: settings.enableImagePosts === true, ...media, images: published.images || [] },
      publishScore: pack.publishScore, marketEvent: pack.marketEvent, qualityReference,
      counter: { date: nextCounter.date, count: nextCounter.count, remaining: Math.max(0, Number(settings.maxDailyPosts || 50) - nextCounter.count) },
      facts: pack.facts, takeaways: pack.takeaways, meta
    });
    if (settings.notifyTelegram) {
      await sendTelegram(`✅ 币安广场发帖成功！\n⏰ 时间：${formatTime(settings.timezone)}\n🪙 币种：${pack.trio.lead.symbol}\n📊 消耗额度：${nextCounter.count}/${settings.maxDailyPosts}\n🔗 帖子链接：${published.url}`).catch(() => null);
    }
    return row;
  } catch (err) {
    const row = appendRun({
      mode, status: 'error', durationMs: Date.now() - startedAt,
      source: pack?.source, lead: pack?.trio?.lead?.symbol, peer: pack?.trio?.peer?.symbol, anchor: pack?.trio?.anchor?.symbol,
      postText: generated?.text, error: err.message || String(err), meta
    });
    const failLimit = Number(settings.maxConsecutiveFailures || 0);
    if (failLimit > 0 && mode !== 'dry-run') {
      const recentLive = listRuns(Math.max(20, failLimit * 3)).filter(r => r.mode !== 'dry-run' && r.status !== 'preview').slice(0, failLimit);
      if (recentLive.length >= failLimit && recentLive.every(r => r.status === 'error')) {
        saveSettings({ enabled: false });
        if (settings.notifyTelegram) {
          await sendTelegram(`⚠️ Binance Square Autopost 已自动暂停\n原因：连续失败 ${failLimit} 次\n最近错误：${err.message || String(err)}`).catch(() => null);
        }
      }
    }
    if (settings.notifyTelegram && mode !== 'dry-run') {
      await sendTelegram(`❌ 币安广场发帖失败\n原因：${err.message || String(err)}`).catch(() => null);
    }
    return row;
  }
}

module.exports = { runOnce, formatTime, hasBannedSymbol, countAutoImagePublishedToday, decideAutoImageForLiveRun };
